//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class academias
    {
        public academias()
        {
            this.article_academias = new HashSet<article_academias>();
            this.book_academias = new HashSet<book_academias>();
            this.project_academias = new HashSet<project_academias>();
            this.recepcional_academias = new HashSet<recepcional_academias>();
            this.scientific_academias = new HashSet<scientific_academias>();
            this.work_academias = new HashSet<work_academias>();
        }
    
        public int ACADEMIA_ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<article_academias> article_academias { get; set; }
        public virtual ICollection<book_academias> book_academias { get; set; }
        public virtual ICollection<project_academias> project_academias { get; set; }
        public virtual ICollection<recepcional_academias> recepcional_academias { get; set; }
        public virtual ICollection<scientific_academias> scientific_academias { get; set; }
        public virtual ICollection<work_academias> work_academias { get; set; }
    }
}
