//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class articles
    {
        public articles()
        {
            this.article_academias = new HashSet<article_academias>();
            this.article_authors = new HashSet<article_authors>();
        }
    
        public int ARTICLE_ID { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> VOLUME { get; set; }
        public Nullable<int> INIT_PAGE { get; set; }
        public Nullable<int> FINAL_PAGE { get; set; }
        public string MAGAZINE { get; set; }
        public string ISSN { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> USER_FK { get; set; }
        public Nullable<int> FILE_FK { get; set; }
        public Nullable<int> ARTICLE_TYPE_FK { get; set; }
        public string DATABASE { get; set; }
        public string DOI { get; set; }
        public Nullable<System.DateTime> APPROVAL_DATE { get; set; }
    
        public virtual ICollection<article_academias> article_academias { get; set; }
        public virtual ICollection<article_authors> article_authors { get; set; }
        public virtual article_types article_types { get; set; }
        public virtual files files { get; set; }
        public virtual users users { get; set; }
    }
}
