//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class authors
    {
        public authors()
        {
            this.article_authors = new HashSet<article_authors>();
            this.book_authors = new HashSet<book_authors>();
            this.project_authors = new HashSet<project_authors>();
            this.receptional_works = new HashSet<receptional_works>();
            this.scientific_authors = new HashSet<scientific_authors>();
        }
    
        public int AUTHOR_ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<article_authors> article_authors { get; set; }
        public virtual ICollection<book_authors> book_authors { get; set; }
        public virtual ICollection<project_authors> project_authors { get; set; }
        public virtual ICollection<receptional_works> receptional_works { get; set; }
        public virtual ICollection<scientific_authors> scientific_authors { get; set; }
    }
}
