//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public books()
        {
            this.book_academias = new HashSet<book_academias>();
            this.book_authors = new HashSet<book_authors>();
        }
    
        public int BOOK_ID { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> BOOK_TYPE_FK { get; set; }
        public Nullable<int> USER_FK { get; set; }
        public Nullable<int> FILE_FK { get; set; }
        public string EDITORIAL { get; set; }
        public string COUNTRY { get; set; }
    
        public virtual ICollection<book_academias> book_academias { get; set; }
        public virtual ICollection<book_authors> book_authors { get; set; }
        public virtual book_types book_types { get; set; }
        public virtual files files { get; set; }
        public virtual users users { get; set; }
    }
}
