//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR.Web.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class micronaEntities : DbContext
    {
        public micronaEntities()
            : base("name=micronaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<academias> academias { get; set; }
        public DbSet<article_academias> article_academias { get; set; }
        public DbSet<article_authors> article_authors { get; set; }
        public DbSet<article_types> article_types { get; set; }
        public DbSet<articles> articles { get; set; }
        public DbSet<authors> authors { get; set; }
        public DbSet<book_academias> book_academias { get; set; }
        public DbSet<book_authors> book_authors { get; set; }
        public DbSet<book_types> book_types { get; set; }
        public DbSet<books> books { get; set; }
        public DbSet<files> files { get; set; }
        public DbSet<project_academias> project_academias { get; set; }
        public DbSet<project_authors> project_authors { get; set; }
        public DbSet<projects> projects { get; set; }
        public DbSet<recepcional_academias> recepcional_academias { get; set; }
        public DbSet<receptional_works> receptional_works { get; set; }
        public DbSet<scientific_academias> scientific_academias { get; set; }
        public DbSet<scientific_authors> scientific_authors { get; set; }
        public DbSet<scientific_production_types> scientific_production_types { get; set; }
        public DbSet<scientific_productions> scientific_productions { get; set; }
        public DbSet<user_types> user_types { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<work_academias> work_academias { get; set; }
        public DbSet<work_authors> work_authors { get; set; }
        public DbSet<work_types> work_types { get; set; }
        public DbSet<works> works { get; set; }
    }
}
