//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class receptional_works
    {
        public receptional_works()
        {
            this.recepcional_academias = new HashSet<recepcional_academias>();
        }
    
        public int RECEPTIONAL_WORK_ID { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> USER_FK { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> FILE_FK { get; set; }
        public string DIRECTOR { get; set; }
        public string ADVISER { get; set; }
        public string CODIRECTION { get; set; }
        public Nullable<int> AUTHOR_FK { get; set; }
    
        public virtual authors authors { get; set; }
        public virtual files files { get; set; }
        public virtual ICollection<recepcional_academias> recepcional_academias { get; set; }
        public virtual users users { get; set; }
    }
}
