//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class scientific_productions
    {
        public scientific_productions()
        {
            this.scientific_academias = new HashSet<scientific_academias>();
            this.scientific_authors = new HashSet<scientific_authors>();
        }
    
        public int SCIENTIFIC_PRODUCTION_ID { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> SCIENTIFIC_PRODUCTION_TYPE_FK { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
    
        public virtual ICollection<scientific_academias> scientific_academias { get; set; }
        public virtual ICollection<scientific_authors> scientific_authors { get; set; }
        public virtual scientific_production_types scientific_production_types { get; set; }
    }
}
