//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class scientific_production_types
    {
        public scientific_production_types()
        {
            this.scientific_productions = new HashSet<scientific_productions>();
        }
    
        public int SCIENTIFIC_PRODUCTION_TYPE_ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<scientific_productions> scientific_productions { get; set; }
    }
}
