//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_types
    {
        public user_types()
        {
            this.users = new HashSet<users>();
        }
    
        public int USER_TYPE_ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<users> users { get; set; }
    }
}
