//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDR.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_authors
    {
        public int idtrabajo_usuario { get; set; }
        public Nullable<int> idTrabajo { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual users users { get; set; }
        public virtual works works { get; set; }
    }
}
